export const URL= "https://abc-api.azurewebsites.net";
export const URL_REGISTER = "/api/auth/register";
export const URL_LOGIN = "/api/auth/login";
export const URL_GET_CATEGORIES = "/api/categories";
export const URL_ADMIN_CATEGORY = '/admin/category'
export const URL_CUSTOMER = "/api/users";
export const URL_ADD_ADDRESS_CUSTOMER = "/api/customer/address";
export const URL_GET_PRODUCTS_BY_CATEGORY = "/api/product/category";
export const URL_GET_PRODUCTS = "/api/products";
export const URL_ADMIN_PRODUCT = '/admin/product';
export const URL_GET_PRODUCT_BY_ID = "/api/product";
export const URL_GET_CART = "/api/carts";